# Generated by Django 4.2.2 on 2023-06-09 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del club')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre del torneo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('hour', models.TimeField(verbose_name='Hora de inicio')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('category', models.CharField(choices=[('Libre', 'Libre'), ('Tercera', 'Tercera'), ('Cuarta', 'Cuarta'), ('Mixtos', 'Mixtos')], max_length=200, null=True, verbose_name='Categoria')),
                ('image', models.ImageField(null=True, upload_to='imagen torneo', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-created'],
            },
        ),
    ]
