# Generated by Django 4.2.2 on 2023-06-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_torneo_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='hour',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
    ]
