# Generated by Django 4.2.2 on 2023-06-09 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=500, verbose_name='Nombre jugador 1')),
                ('lastname_1', models.CharField(max_length=500, verbose_name='Apellido jugador 1')),
                ('phone_1', models.IntegerField(verbose_name='Teléfono jugador 1')),
                ('mail_1', models.EmailField(max_length=500, verbose_name='Correo jugador 1')),
                ('name_2', models.CharField(max_length=500, verbose_name='Nombre jugador 2')),
                ('lastname_2', models.CharField(max_length=500, verbose_name='Apellido jugador 2')),
                ('phone_2', models.IntegerField(verbose_name='Teléfono jugador 2')),
                ('mail_2', models.EmailField(max_length=500, verbose_name='Correo jugador 2')),
                ('category', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Mixto', 'Mixto')], max_length=200, null=True, verbose_name='Categoria')),
                ('level', models.CharField(choices=[('Libre', 'Libre'), ('Tercera', 'Tercera'), ('Cuarta', 'Cuarta'), ('Mixtos', 'Mixtos')], max_length=200, null=True, verbose_name='Nivel')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-created'],
            },
        ),
    ]
